### ISSUE TITLE
Bracket misplaced in casting comparison from java to kotlin

### ISSUE THREAD

**Issue by ishaan1995** [MindorksOpenSource/from-java-to-kotlin#18]
In this java to kotlin comparison
> Java

```java
if(object instanceof Car){
}
Car car = (Car) object;
```

> Kotlin

```kotlin
if (object is Car) {
}
var car = object as Car
```

---

 Shouldn't the casting be inside the braces, i.e

> Java

```java
if(object instanceof Car){
    Car car = (Car) object;
}
```

> Kotlin

```kotlin
if (object is Car) {
    var car = object as Car
}
```

**Comment by tedyoung** [comment]
That's what I thought at first, but then I realized that it's two separate things being translated, the first is the boolean expression to see if an instance is from a class, so:

Java:
```java
if (object instanceof Car){
}
```

in Kotlin is:
```kotlin
if (object is Car) {
}
```

and the explicit cast example:
```java
Car car = (Car) object;
```

in Kotlin is:
```kotlin
var car = object as Car
```

I agree this is confusing and think they shouldn't be grouped like this to make it more clear.
