### ISSUE TITLE
I don't understand last section Java and Kotlin comparision

### ISSUE THREAD

**Issue by altaf933** [MindorksOpenSource/from-java-to-kotlin#5]
```
Java
public class Utils {

    private Utils() { 
      // This utility class is not publicly instantiable 
    }
    
    public static int triple(int value) {
        return 3 * value;
    }
    
}

int result = Utils.triple(3);
Kotlin
fun Int.triple(): Int {
  return this * 3
}

var result = 3.triple()
```

var result = 3.triple() is it same function as in Java called Utils.triple(3) ?
If yes than **3**  how can be an object ?

**Comment by amitshekhariitbhu** [comment]
@altaf933 This is possible in Kotlin as it supports extension feature.

**Comment by altaf933** [comment]
**this** function inside an extension function corresponding to receiver object. I got the receiver` fun Int.triple() ` and thanks for prompt reply.
